/* eslint-disable no-undef */
// Define your difficulty anchors — add as many as you want
const difficultyAnchors = [
  // Early levels — short, common words dominate
  { level: 1,  dist: { one: 0.20, two: 0.30, three: 0.30, four: 0.15, five: 0.05, six: 0.00, seven: 0.00, eight: 0.00, nine: 0.00, ten: 0.00 } },
  { level: 5,  dist: { one: 0.10, two: 0.20, three: 0.30, four: 0.25, five: 0.10, six: 0.05, seven: 0.00, eight: 0.00, nine: 0.00, ten: 0.00 } },
  { level: 10, dist: { one: 0.05, two: 0.10, three: 0.20, four: 0.30, five: 0.20, six: 0.10, seven: 0.05, eight: 0.00, nine: 0.00, ten: 0.00 } },

  // Mid levels — medium words take over, long words introduced
  { level: 15, dist: { one: 0.00, two: 0.05, three: 0.15, four: 0.25, five: 0.25, six: 0.15, seven: 0.10, eight: 0.05, nine: 0.00, ten: 0.00 } },
  { level: 20, dist: { one: 0.00, two: 0.05, three: 0.10, four: 0.20, five: 0.25, six: 0.20, seven: 0.10, eight: 0.05, nine: 0.05, ten: 0.00 } },
  { level: 25, dist: { one: 0.00, two: 0.00, three: 0.10, four: 0.15, five: 0.20, six: 0.20, seven: 0.15, eight: 0.10, nine: 0.05, ten: 0.05 } },

  // Upper levels — long and complex words dominate
  { level: 30, dist: { one: 0.00, two: 0.00, three: 0.05, four: 0.10, five: 0.15, six: 0.20, seven: 0.20, eight: 0.15, nine: 0.10, ten: 0.05 } },
  { level: 35, dist: { one: 0.00, two: 0.00, three: 0.05, four: 0.05, five: 0.10, six: 0.15, seven: 0.20, eight: 0.20, nine: 0.15, ten: 0.10 } },
  { level: 40, dist: { one: 0.00, two: 0.00, three: 0.00, four: 0.05, five: 0.10, six: 0.15, seven: 0.20, eight: 0.20, nine: 0.15, ten: 0.15 } },
  { level: 45, dist: { one: 0.00, two: 0.00, three: 0.00, four: 0.05, five: 0.05, six: 0.10, seven: 0.15, eight: 0.25, nine: 0.20, ten: 0.20 } },

  // Level 50 — elite, only long words
  { level: 50, dist: { one: 0.00, two: 0.00, three: 0.00, four: 0.00, five: 0.05, six: 0.05, seven: 0.10, eight: 0.20, nine: 0.30, ten: 0.30 } },
];

const MAX_HARD_LEVEL = difficultyAnchors.at(-1).level;

// Smoothly interpolate between two anchors
const interpolateDist = (a, b, t) => {
  const keys = Object.keys(a);
  return Object.fromEntries(keys.map(k => [k, a[k] + (b[k] - a[k]) * t]));
};

// Get distribution for any level, clamped at max hardness
const getDistribution = (level) => {
  const clamped = Math.min(level, MAX_HARD_LEVEL);

  // Exact anchor match
  const exact = difficultyAnchors.find(a => a.level === clamped);
  if (exact) return exact.dist;

  // Find surrounding anchors and interpolate
  const lower = [...difficultyAnchors].reverse().find(a => a.level < clamped);
  const upper = difficultyAnchors.find(a => a.level > clamped);

  if (!lower) return difficultyAnchors[0].dist;
  if (!upper) return difficultyAnchors.at(-1).dist;

  const t = (clamped - lower.level) / (upper.level - lower.level);
  return interpolateDist(lower.dist, upper.dist, t);
};

export const generateWords = async (count = 50) => {
  const { user } = await chrome.storage.local.get(["user"]);
  const level = user?.stats?.level?.level || 1

  const distribution = getDistribution(level);

  const pick = (arr, n) =>
    n <= 0 ? [] : [...arr].sort(() => Math.random() - 0.5).slice(0, n);

  const counts = {
    one:   Math.round(count * distribution.one),
    two:   Math.round(count * distribution.two),
    three: Math.round(count * distribution.three),
    four:  Math.round(count * distribution.four),
    five:  Math.round(count * distribution.five),
    six:   Math.round(count * distribution.six),
    seven: Math.round(count * distribution.seven),
    eight: Math.round(count * distribution.eight),
    nine:  Math.round(count * distribution.nine),
    ten:   Math.round(count * distribution.ten),
  };

  // Fix rounding drift
  const total = Object.values(counts).reduce((a, b) => a + b, 0);
  counts.four += count - total;

  const words = [
    ...pick(commonWords.one,   counts.one),
    ...pick(commonWords.two,   counts.two),
    ...pick(commonWords.three, counts.three),
    ...pick(commonWords.four,  counts.four),
    ...pick(commonWords.five,  counts.five),
    ...pick(commonWords.six,  counts.six),
    ...pick(commonWords.seven,  counts.seven),
    ...pick(commonWords.eight,  counts.eight),
    ...pick(commonWords.nine,  counts.nine),
    ...pick(commonWords.ten,  counts.ten),
  ].sort(() => Math.random() - 0.5);

  return words.map((word, i) => ({ word, key: `${Date.now()}-${i}` }));
};


export const commonWords = {
  one: [
    'a', 'i',
  ],
  two: [
    'am', 'an', 'as', 'at', 'be', 'by', 'do', 'go', 'he', 'hi',
    'if', 'in', 'is', 'it', 'me', 'my', 'no', 'of', 'on', 'or',
    'so', 'to', 'up', 'us', 'we',
    'ok', 'oh', 'ah', 'ox', 'ax', 'ex', 'id', 'ok', 'ok',
  ],
  three: [
    'the', 'and', 'for', 'are', 'but', 'not', 'you', 'all', 'can', 'her',
    'was', 'one', 'our', 'out', 'day', 'get', 'has', 'him', 'his', 'how',
    'man', 'new', 'now', 'old', 'see', 'two', 'way', 'who', 'boy', 'did',
    'its', 'let', 'put', 'say', 'she', 'too', 'use', 'run', 'eat', 'big',
    'fox', 'dog', 'add', 'win', 'fly',
    'act', 'age', 'ago', 'aid', 'aim', 'air', 'any', 'arm', 'art', 'ask',
    'bad', 'bag', 'ban', 'bar', 'bat', 'bed', 'bit', 'box', 'bus', 'buy',
    'car', 'cat', 'cup', 'cut', 'end', 'eye', 'far', 'few', 'fun', 'gas',
    'god', 'got', 'gun', 'gut', 'guy', 'had', 'hat', 'hit', 'hot', 'ice',
    'job', 'joy', 'key', 'kid', 'lap', 'law', 'lay', 'led', 'leg', 'log',
    'lot', 'low', 'map', 'may', 'mix', 'mom', 'mud', 'net', 'nor', 'odd',
    'off', 'own', 'pay', 'pie', 'pig', 'pin', 'pit', 'pop', 'pot', 'raw',
    'red', 'rid', 'row', 'set', 'sir', 'sit', 'six', 'sky', 'son', 'sub',
    'sum', 'sun', 'tax', 'ten', 'tie', 'tip', 'top', 'try', 'tub', 'van',
    'via', 'war', 'wet', 'why', 'yet',
  ],
  four: [
    'that', 'with', 'have', 'this', 'will', 'your', 'from', 'they', 'know', 'want',
    'been', 'good', 'much', 'some', 'time', 'very', 'when', 'come', 'here', 'just',
    'like', 'five', 'make', 'many', 'more', 'only', 'over', 'such', 'take', 'than',
    'them', 'well', 'were', 'what', 'also', 'back', 'call', 'came', 'each', 'even',
    'find', 'gave', 'give', 'goes', 'hand', 'help', 'high', 'hold', 'home', 'keep',
    'lazy', 'test', 'type', 'race', 'rank', 'flow', 'bold', 'soft', 'cool',
    'dark', 'warm', 'fast', 'slow', 'year', 'part', 'play', 'move', 'live', 'show',
    'open', 'walk', 'read', 'grow', 'work', 'case', 'week', 'feel', 'word', 'port',
    'plug', 'font', 'icon',
    'able', 'area', 'army', 'baby', 'ball', 'band', 'bank', 'base', 'bath', 'bear',
    'beat', 'bell', 'best', 'bill', 'bite', 'blow', 'blue', 'body', 'bone', 'book',
    'born', 'both', 'burn', 'busy', 'city', 'club', 'code', 'copy', 'core', 'cost',
    'data', 'days', 'dead', 'deal', 'deep', 'desk', 'door', 'down', 'draw', 'drop',
    'drug', 'dual', 'dust', 'duty', 'earn', 'east', 'easy', 'edge', 'else', 'exam',
    'exit', 'face', 'fact', 'fail', 'fair', 'fall', 'farm', 'fear', 'feet', 'fill',
    'film', 'fire', 'firm', 'fish', 'flag', 'flat', 'flew', 'flip', 'food', 'foot',
    'form', 'free', 'fuel', 'full', 'gain', 'game', 'gate', 'gear', 'gift', 'girl',
    'glad', 'goal', 'gold', 'grab', 'gray', 'grid', 'grip', 'grow', 'gulf', 'half',
    'hall', 'hard', 'harm', 'hate', 'have', 'head', 'heat', 'heel', 'hell', 'hero',
    'hide', 'hill', 'hint', 'hire', 'hole', 'hook', 'hope', 'horn', 'host', 'hour',
    'huge', 'hunt', 'hurt', 'idea', 'inch', 'into', 'iron', 'item', 'jail', 'join',
    'joke', 'jump', 'jury', 'kick', 'kill', 'kind', 'king', 'kiss', 'knee', 'lack',
    'laid', 'lake', 'land', 'lane', 'last', 'late', 'lead', 'leaf', 'lean', 'leap',
    'left', 'lens', 'life', 'lift', 'link', 'list', 'load', 'lock', 'long', 'look',
    'loop', 'lord', 'lose', 'loss', 'loud', 'love', 'luck', 'lump', 'lung', 'made',
    'mail', 'main', 'mall', 'mark', 'mass', 'meal', 'mean', 'meet', 'mild', 'mile',
    'milk', 'mill', 'mind', 'mine', 'miss', 'mode', 'moon', 'most', 'must', 'name',
    'navy', 'near', 'neck', 'need', 'news', 'next', 'nice', 'nine', 'node', 'none',
    'noon', 'norm', 'nose', 'note', 'null', 'oath', 'once', 'ones', 'onto', 'oral',
    'ours', 'owns', 'pace', 'pack', 'page', 'paid', 'pain', 'pair', 'palm', 'past',
    'path', 'peak', 'pick', 'pile', 'pipe', 'plan', 'plot', 'plus', 'poll', 'pond',
    'pool', 'poor', 'post', 'pour', 'pull', 'pump', 'pure', 'push', 'quit', 'rail',
    'rain', 'real', 'rent', 'rest', 'rice', 'rich', 'ride', 'ring', 'rise', 'risk',
    'road', 'rock', 'role', 'roll', 'roof', 'room', 'root', 'rose', 'rude', 'rule',
    'rush', 'rust', 'safe', 'sail', 'sale', 'salt', 'same', 'sand', 'save', 'scan',
    'seal', 'seat', 'seed', 'seek', 'self', 'sell', 'send', 'sent', 'ship', 'shoe',
    'shop', 'shot', 'shut', 'sick', 'side', 'sign', 'silk', 'sing', 'sink', 'site',
    'size', 'skin', 'skip', 'slim', 'slip', 'slot', 'snap', 'snow', 'soap', 'sock',
    'soil', 'sold', 'sole', 'song', 'soon', 'sort', 'soul', 'soup', 'span', 'spin',
    'spot', 'star', 'stay', 'stem', 'step', 'stop', 'suit', 'sure', 'swim', 'tail',
    'tall', 'tank', 'tape', 'task', 'team', 'tear', 'tell', 'tend', 'term', 'that',
    'then', 'thus', 'tide', 'till', 'tiny', 'tire', 'told', 'toll', 'tone', 'took',
    'tool', 'tops', 'toss', 'tour', 'town', 'toys', 'trap', 'tree', 'trim', 'trip',
    'true', 'tube', 'tune', 'turn', 'twin', 'ugly', 'unit', 'upon', 'used', 'user',
    'vary', 'vast', 'vest', 'view', 'vibe', 'void', 'vote', 'wade', 'wage', 'wait',
    'wake', 'wall', 'wand', 'want', 'ward', 'ware', 'warp', 'wash', 'wave', 'weak',
    'wean', 'wear', 'weld', 'went', 'west', 'wide', 'wife', 'wild', 'wind', 'wine',
    'wing', 'wire', 'wise', 'wish', 'with', 'woke', 'wolf', 'wood', 'wore', 'worn',
    'wrap', 'writ', 'yard', 'zone',
  ],
  five: [
    'quick', 'panel', 'frame', 'pixel', 'sharp', 'clean', 'clear',
    'light', 'heavy', 'solid', 'dense', 'loose', 'tight', 'quiet', 'score', 'skill',
    'speed', 'focus', 'mount', 'board', 'sound', 'write', 'words',
    'cable', 'rapid', 'local', 'bring', 'begin', 'offer', 'place',
    'power', 'value',
    'about', 'above', 'abuse', 'after', 'again', 'agent', 'agree', 'ahead', 'allow',
    'alone', 'along', 'alter', 'angel', 'angry', 'anime', 'apple', 'apply', 'arena',
    'argue', 'arise', 'array', 'aside', 'asset', 'avoid', 'award', 'aware', 'awful',
    'basic', 'basis', 'batch', 'beach', 'beast', 'belly', 'bench', 'birth', 'black',
    'blade', 'blame', 'blank', 'blast', 'blaze', 'bleed', 'bless', 'blind', 'block',
    'bloom', 'blown', 'blues', 'blunt', 'bound', 'brain', 'brand', 'brave', 'bread',
    'break', 'breed', 'brief', 'broke', 'brook', 'brown', 'brush', 'buddy', 'build',
    'built', 'burst', 'buyer', 'carry', 'catch', 'cause', 'chain', 'chair', 'chaos',
    'charm', 'chart', 'chase', 'check', 'chief', 'child', 'chose', 'chunk', 'cited',
    'civil', 'claim', 'clash', 'class', 'click', 'climb', 'clock', 'close', 'cloud',
    'coach', 'coast', 'color', 'comic', 'comma', 'coral', 'count', 'court', 'cover',
    'crack', 'craft', 'crash', 'crazy', 'creek', 'crime', 'cross', 'crowd', 'cruel',
    'crush', 'curve', 'cycle', 'daily', 'dance', 'death', 'debug', 'delay', 'delta',
    'depth', 'dirty', 'disco', 'dodge', 'doubt', 'dough', 'draft', 'drain', 'drama',
    'drank', 'dream', 'dress', 'drink', 'drive', 'drove', 'drunk', 'dryer', 'eagle',
    'early', 'earth', 'eight', 'elite', 'email', 'empty', 'enjoy', 'enter', 'entry',
    'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra', 'faint', 'faith',
    'false', 'fancy', 'fatal', 'fault', 'feast', 'fetch', 'field', 'fight', 'final',
    'first', 'fixed', 'flame', 'flash', 'fleet', 'flesh', 'float', 'flood', 'floor',
    'floss', 'flour', 'fluid', 'flush', 'flute', 'force', 'forge', 'forth', 'forum',
    'found', 'fresh', 'front', 'frost', 'froze', 'fruit', 'fully', 'funny', 'glide',
    'glint', 'globe', 'gloss', 'glove', 'glyph', 'grace', 'grade', 'grand', 'grant',
    'grasp', 'grass', 'grave', 'great', 'green', 'greet', 'grief', 'grind', 'groan',
    'gross', 'group', 'grove', 'guard', 'guess', 'guest', 'guide', 'guild', 'guilt',
    'gusto', 'hands', 'happy', 'harsh', 'haste', 'heart', 'hedge', 'hence', 'herbs',
    'hobby', 'honor', 'horse', 'hotel', 'house', 'human', 'humor', 'hurry', 'hutch',
    'image', 'inbox', 'index', 'indie', 'input', 'intro', 'issue', 'ivory', 'japan',
    'judge', 'juice', 'jumpy', 'karma', 'label', 'lance', 'large', 'laser', 'later',
    'laugh', 'layer', 'learn', 'lease', 'least', 'leave', 'level', 'limit', 'liner',
    'liver', 'logic', 'login', 'lower', 'lucky', 'lunar', 'lunch', 'lyric', 'magic',
    'major', 'maker', 'march', 'match', 'mayor', 'media', 'mercy', 'merge', 'metal',
    'meter', 'micro', 'might', 'model', 'money', 'month', 'moral', 'motor', 'mouse',
    'mouth', 'multi', 'music', 'naive', 'night', 'noise', 'north', 'notes', 'novel',
    'nurse', 'nylon', 'occur', 'ocean', 'often', 'olive', 'onset', 'optic', 'orbit',
    'order', 'other', 'ounce', 'outer', 'oxide', 'ozone', 'peace', 'peach', 'pearl',
    'penny', 'perch', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch',
    'pivot', 'plain', 'plane', 'plant', 'plate', 'plaza', 'plead', 'pluck', 'plumb',
    'plunge','point', 'polar', 'poppy', 'press', 'price', 'pride', 'prime', 'print',
    'prior', 'prize', 'probe', 'proof', 'prose', 'proud', 'prove', 'proxy', 'pulse',
    'punch', 'pupil', 'purge', 'query', 'queue', 'quote', 'radar', 'raise', 'range',
    'ratio', 'reach', 'ready', 'realm', 'rebel', 'refer', 'reign', 'relax', 'relay',
    'renew', 'repay', 'rerun', 'reset', 'rider', 'ridge', 'right', 'rigid', 'risky',
    'rival', 'river', 'robin', 'robot', 'rocky', 'rouge', 'rough', 'round', 'route',
    'rover', 'ruled', 'ruler', 'rural', 'sadly', 'saint', 'salad', 'sauce', 'scale',
    'scene', 'scout', 'setup', 'seven', 'shade', 'shake', 'shape', 'share', 'shelf',
    'shift', 'shine', 'shirt', 'shock', 'shoot', 'short', 'shout', 'sight', 'since',
    'sixth', 'sixty', 'sized', 'skate', 'skill', 'sleep', 'slice', 'slide', 'slope',
    'smart', 'smile', 'smoke', 'snake', 'sneak', 'solar', 'solve', 'sorry', 'south',
    'space', 'spark', 'speak', 'spend', 'spill', 'spine', 'split', 'spoke', 'spook',
    'sport', 'spray', 'squad', 'stack', 'staff', 'stage', 'stain', 'stake', 'stale',
    'stand', 'stark', 'start', 'state', 'stave', 'steel', 'steep', 'stern', 'stick',
    'stiff', 'still', 'stock', 'stone', 'stood', 'store', 'storm', 'story', 'stove',
    'strap', 'stray', 'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite',
    'surge', 'swamp', 'swear', 'sweet', 'swept', 'swing', 'swipe', 'swoop', 'sword',
    'table', 'taken', 'taste', 'teach', 'teeth', 'tempo', 'tense', 'tenth', 'terms',
    'their', 'theme', 'there', 'thick', 'thing', 'think', 'third', 'those', 'three',
    'threw', 'throw', 'thumb', 'tiger', 'timer', 'tired', 'title', 'today', 'token',
    'topic', 'total', 'touch', 'tough', 'tower', 'trace', 'track', 'trade', 'train',
    'trait', 'trash', 'treat', 'trend', 'trial', 'trick', 'tried', 'troop', 'trout',
    'truck', 'truly', 'trust', 'truth', 'tuple', 'twice', 'twist', 'typed', 'ultra',
    'uncle', 'under', 'unify', 'until', 'upper', 'usage', 'valid', 'vapor', 'verse',
    'video', 'vigor', 'viral', 'virus', 'visit', 'vista', 'vital', 'voice', 'voter',
    'vowel', 'wagon', 'watch', 'water', 'weigh', 'weird', 'whale', 'wheat', 'wheel',
    'where', 'which', 'while', 'white', 'whole', 'whose', 'wider', 'width', 'women',
    'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wrist', 'wrong', 'yacht',
    'yield', 'young', 'youth', 'zebra',
  ],
  six: [
    'switch', 'finger', 'change', 'action', 'signal', 'screen',
    'layout', 'linear', 'clicky', 'smooth', 'people', 'appear',
    'happen', 'window', 'global', 'static', 'active',
    'access', 'actual', 'afford', 'almost', 'always', 'amount', 'animal', 'answer',
    'around', 'assert', 'attach', 'attack', 'autumn', 'avenue', 'battle', 'beauty',
    'became', 'before', 'behind', 'belief', 'belong', 'better', 'beyond', 'binary',
    'border', 'bottle', 'bottom', 'bounce', 'branch', 'breach', 'bridge', 'bright',
    'broken', 'bronze', 'budget', 'buffer', 'button', 'carbon', 'center', 'cherry',
    'choice', 'choose', 'chosen', 'circle', 'client', 'closed', 'coffee', 'column',
    'combat', 'common', 'custom', 'damage', 'danger', 'decade', 'decide', 'decode',
    'deeper', 'defect', 'define', 'delete', 'deploy', 'design', 'detail', 'detect',
    'device', 'differ', 'dinner', 'direct', 'domain', 'double', 'driven', 'driver',
    'during', 'earned', 'easily', 'effect', 'effort', 'either', 'enable', 'encode',
    'energy', 'engage', 'engine', 'enough', 'entity', 'escape', 'events', 'except',
    'expand', 'expect', 'expert', 'export', 'extend', 'fabric', 'factor', 'family',
    'filter', 'finish', 'flight', 'follow', 'footer', 'forest', 'format', 'former',
    'foster', 'fought', 'fourth', 'freeze', 'french', 'frozen', 'future', 'garden',
    'gentle', 'golden', 'graded', 'gravel', 'ground', 'growth', 'guitar', 'handle',
    'header', 'height', 'hidden', 'highly', 'honest', 'hosted', 'impact', 'import',
    'income', 'indeed', 'inject', 'inside', 'intent', 'invite', 'island', 'itself',
    'jersey', 'jitter', 'launch', 'leader', 'lender', 'listen', 'loaded', 'lookup',
    'market', 'master', 'matter', 'mental', 'method', 'mirror', 'mobile', 'modern',
    'module', 'moment', 'mostly', 'motion', 'muscle', 'mutual', 'nearly', 'needle',
    'negate', 'nested', 'neural', 'normal', 'notice', 'notify', 'number', 'object',
    'obtain', 'offset', 'online', 'option', 'orange', 'origin', 'output', 'packet',
    'parent', 'parser', 'passed', 'patent', 'phrase', 'plenty', 'pocket', 'policy',
    'portal', 'postal', 'prefer', 'pretty', 'priest', 'profit', 'prompt', 'proper',
    'proven', 'public', 'purple', 'queued', 'rabbit', 'random', 'rather', 'reason',
    'record', 'reduce', 'reflect', 'reload', 'remote', 'remove', 'render', 'repeat',
    'replay', 'report', 'reveal', 'revert', 'review', 'reward', 'ribbon', 'robust',
    'router', 'safety', 'salary', 'search', 'second', 'secret', 'secure', 'select',
    'sender', 'server', 'should', 'simple', 'single', 'slider', 'slowly', 'source',
    'stable', 'status', 'sticky', 'stored', 'stream', 'street', 'strict', 'string',
    'strong', 'struct', 'submit', 'suburb', 'summer', 'sunset', 'supply', 'survey',
    'symbol', 'syntax', 'system', 'talent', 'target', 'thread', 'toggle', 'tooled',
    'topics', 'traced', 'traded', 'tribal', 'triple', 'trophy', 'tunnel', 'turtle',
    'twitch', 'typing', 'unique', 'unlock', 'update', 'upload', 'useful', 'vector',
    'vendor', 'verbal', 'verify', 'viable', 'viewer', 'violet', 'vision', 'visual',
    'volume', 'warmer', 'wealth', 'weekly', 'weight', 'widely', 'widget', 'winter',
    'within', 'wonder', 'worker', 'yellow',
  ],
  seven: [
    'testing', 'typing', 'letters', 'keycap', 'tactile',
    'connect', 'monitor', 'display', 'company', 'produce',
    'provide', 'require', 'request', 'convert', 'support', 'process',
    'account', 'achieve', 'address', 'advance', 'already', 'ambient', 'analyze',
    'another', 'arrange', 'attract', 'average', 'backend', 'balance', 'battery',
    'because', 'benefit', 'between', 'browser', 'builder', 'caching', 'capture',
    'cascade', 'catalog', 'central', 'circuit', 'cleanup', 'cluster', 'combine',
    'command', 'compact', 'compose', 'compute', 'concept', 'conduct', 'confirm',
    'console', 'contact', 'content', 'context', 'control', 'counter', 'country',
    'counter', 'courier', 'covered', 'current', 'default', 'desktop', 'develop',
    'digital', 'disable', 'discuss', 'dismiss', 'dynamic', 'element', 'emotion',
    'encrypt', 'enforce', 'enhance', 'example', 'execute', 'express', 'extract',
    'feature', 'feeling', 'fighter', 'finally', 'flatten', 'forward', 'freedom',
    'gateway', 'general', 'generic', 'gesture', 'graphic', 'handler', 'history',
    'hosting', 'however', 'imagine', 'improve', 'include', 'initial', 'install',
    'integer', 'invalid', 'iterate', 'journey', 'justify', 'keyword', 'kitchen',
    'landing', 'latency', 'learned', 'library', 'limited', 'loading', 'logical',
    'machine', 'managed', 'mapping', 'maximum', 'measure', 'message', 'minimum',
    'missing', 'mission', 'mistake', 'mixture', 'network', 'neutral', 'nothing',
    'noticed', 'numeric', 'objects', 'obvious', 'offline', 'ongoing', 'opinion',
    'optical', 'options', 'ordered', 'outdoor', 'overlay', 'package', 'parsing',
    'passive', 'pattern', 'payment', 'pending', 'perform', 'perhaps', 'persist',
    'picture', 'pointer', 'polling', 'popular', 'preview', 'primary', 'private',
    'problem', 'profile', 'program', 'project', 'protect', 'publish', 'purpose',
    'quality', 'quickly', 'ranking', 'rebuild', 'receive', 'refresh', 'regular',
    'related', 'release', 'replace', 'respect', 'restart', 'restore', 'results',
    'routing', 'running', 'runtime', 'satisfy', 'scatter', 'section', 'segment',
    'sending', 'service', 'session', 'setting', 'several', 'sharing', 'silence',
    'similar', 'smaller', 'snippet', 'sorting', 'spacing', 'speaker', 'spinner',
    'staging', 'startup', 'storage', 'stretch', 'student', 'surface', 'through',
    'timeout', 'toolbar', 'tooltip', 'tracker', 'traffic', 'trained', 'trigger',
    'trusted', 'turbine', 'unblock', 'uniform', 'unknown', 'updated', 'upgrade',
    'version', 'warning', 'website', 'welcome', 'whether', 'without', 'working',
    'writing',
  ],
  eight: [
    'keyboard', 'practice', 'response', 'feedback', 'reliable',
    'consider', 'remember', 'accurate', 'function', 'stabilizer',
    'absolute', 'abstract', 'activity', 'addition', 'advanced', 'affected',
    'alphabet', 'analysis', 'animated', 'argument', 'assembly', 'assigned',
    'attached', 'attacker', 'auditing', 'authored', 'balanced', 'baseline',
    'blocking', 'brackets', 'breaking', 'browsers', 'building', 'caching',
    'callback', 'captured', 'carousel', 'category', 'centered', 'changing',
    'checking', 'checkout', 'children', 'circular', 'codebase', 'collapse',
    'complete', 'compiler', 'compound', 'computed', 'concepts', 'connects',
    'constant', 'controls', 'coverage', 'creating', 'database', 'datetime',
    'decision', 'deployed', 'describe', 'designed', 'detected', 'directed',
    'disabled', 'dispatch', 'distance', 'division', 'document', 'dominant',
    'download', 'dragging', 'dropdown', 'duration', 'encoding', 'endpoint',
    'enhanced', 'equality', 'evaluate', 'extended', 'external', 'fastener',
    'featured', 'filtered', 'flexible', 'floating', 'followed', 'frontend',
    'generate', 'gradient', 'grouping', 'handling', 'hardware', 'hostname',
    'identity', 'imported', 'inactive', 'included', 'infinite', 'instance',
    'internet', 'interval', 'iterator', 'keyboard', 'language', 'launched',
    'learning', 'listener', 'location', 'matching', 'measured', 'metadata',
    'mobility', 'modifier', 'multiple', 'mutation', 'navigate', 'negative',
    'notation', 'observer', 'operator', 'ordering', 'overflow', 'override',
    'parallel', 'passable', 'password', 'platform', 'playback', 'pointing',
    'position', 'prefixed', 'previous', 'priority', 'progress', 'property',
    'protocol', 'provider', 'readable', 'realtime', 'receiver', 'redirect',
    'register', 'rejected', 'relation', 'required', 'resource', 'resolved',
    'reusable', 'revision', 'rollback', 'rotating', 'scaffold', 'schedule',
    'security', 'selector', 'separate', 'sequence', 'services', 'settings',
    'shortcut', 'skeleton', 'solution', 'sortable', 'specific', 'spectrum',
    'standard', 'starting', 'strategy', 'streamed', 'strength', 'subquery',
    'subtotal', 'tailored', 'template', 'terminal', 'throttle', 'timeline',
    'together', 'tracking', 'transfer', 'triggers', 'trimming', 'truncate',
    'tutorial', 'underline', 'unloaded', 'updating', 'username', 'validate',
    'variable', 'velocity', 'viewport', 'watching', 'wildcard', 'workflow',
  ],
  nine: [
    'precision', 'challenge', 'sentences', 'efficient',
    'animation', 'component', 'interface', 'formatter',
    'algorithm', 'alignment', 'allowance', 'alongside', 'ambiguous', 'analytics',
    'annotated', 'anonymous', 'assertion', 'asymmetry', 'automatic', 'available',
    'awareness', 'bandwidth', 'beautiful', 'benchmark', 'blueprint', 'bootstrap',
    'broadcast', 'calculate', 'carefully', 'character', 'clipboard', 'collapsed',
    'collected', 'combining', 'completed', 'computing', 'connected', 'connector',
    'container', 'converted', 'correctly', 'customize', 'dashboard', 'debugging',
    'decorated', 'delivered', 'detection', 'developer', 'deviation', 'dimension',
    'direction', 'discovery', 'duplicate', 'effective', 'elaborate', 'encrypted',
    'estimated', 'evaluated', 'exception', 'execution', 'exhausted', 'expecting',
    'extending', 'extracted', 'filtering', 'framework', 'frequency', 'geography',
    'gradually', 'hardcoded', 'hierarchy', 'highlight', 'identical', 'immediate',
    'implement', 'important', 'inclusion', 'increment', 'indicator', 'inherited',
    'initially', 'injection', 'installed', 'integrity', 'iteration', 'justified',
    'knowledge', 'landscape', 'lifecycle', 'listeners', 'literally', 'localhost',
    'marketing', 'mechanism', 'migration', 'milestone', 'motivated', 'namespace',
    'necessary', 'networked', 'normalize', 'numerical', 'objective', 'observers',
    'operating', 'optimized', 'organized', 'overwrite', 'paginated', 'parameter',
    'partially', 'permitted', 'persisted', 'placement', 'populated', 'potential',
    'primarily', 'primitive', 'principal', 'privilege', 'processed', 'processor',
    'profiling', 'protected', 'prototype', 'published', 'qualified', 'quantized',
    'realistic', 'recursive', 'reference', 'refreshed', 'regulated', 'rendering',
    'retrieval', 'revisited', 'scheduler', 'selection', 'separated', 'serialize',
    'simulated', 'singleton', 'specified', 'stability', 'statement', 'streaming',
    'structure', 'substring', 'symmetric', 'technique', 'temporary', 'threshold',
    'timestamp', 'tokenized', 'transform', 'transpose', 'triggered', 'truncated',
    'universal', 'unlimited', 'unrelated', 'validated', 'variation', 'versatile',
    'whitelist', 'workspace',
  ],
  ten: [
    'satisfying', 'leaderboard', 'consistent', 'competition',
    'responsive', 'accessible', 'compressed', 'transition',
    'fullscreen', 'stylesheet', 'typescript', 'javascript',
    'middleware', 'controller', 'pagination', 'validation',
    'screenshot', 'background', 'improvement', 'alternative',
    'absolutely', 'accomplish', 'accumulate', 'additional', 'addressing', 'algorithms',
    'allocation', 'annotation', 'appearance', 'applicable', 'appreciate', 'arithmetic',
    'assembling', 'assessment', 'associated', 'assumption', 'attachment', 'attempting',
    'attributed', 'authorized', 'automation', 'benchmarks', 'bottleneck', 'breakpoint',
    'capability', 'categories', 'characters', 'checkpoint', 'collection', 'complexity',
    'comprehend', 'conceptual', 'concurrent', 'configured', 'connection', 'constraint',
    'contextual', 'continuing', 'conversion', 'coordinate', 'correction', 'cumulative',
    'customized', 'decompress', 'definition', 'deployment', 'deprecated', 'descriptor',
    'determined', 'dictionary', 'difference', 'difficulty', 'discovered', 'dispatcher',
    'displaying', 'documented', 'efficiency', 'encryption', 'evaluation', 'eventually',
    'everything', 'exceptions', 'expression', 'generation', 'identifier', 'illuminate',
    'implements', 'indicating', 'individual', 'initialize', 'integrated', 'interfaces',
    'internally', 'interprets', 'invitation', 'iterations', 'javascript', 'leadership',
    'limitation', 'manageable', 'management', 'meaningful', 'mechanisms', 'migrations',
    'modifiable', 'monitoring', 'motivation', 'navigation', 'normalized', 'observable',
    'operations', 'optimistic', 'optimizing', 'outperform', 'parametric', 'permission',
    'persistent', 'population', 'prediction', 'preference', 'processing', 'projection',
    'properties', 'publishing', 'qualifying', 'randomized', 'reasonable', 'rebuilding',
    'refactored', 'registered', 'reliability', 'repeatedly', 'replicated', 'requesting',
    'resilience', 'resolution', 'restricted', 'retrieving', 'scheduling', 'scrollable',
    'serialized', 'simplified', 'simulation', 'standalone', 'statistics', 'submission',
    'successful', 'supporting', 'terminated', 'throughout', 'timestamps', 'tokenizing',
    'transforms', 'triggering', 'understand', 'unexpected', 'unreliable', 'unresolved',
    'updateable', 'usefulness', 'versioning', 'virtualdom', 'visibility', 'workspaces',
  ],
};